[package]
name = "ewext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[profile.release]
lto = true
strip = true

[dependencies]
libloading = "0.8.5"
backtrace = "0.3.74"
noita_api_macro = {path = "noita_api_macro"}
